In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#China 
china_10y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\China 10-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
china_10y = china_10y.set_index('Date').sort_index()
china_10y.columns = ['China_10Y']
china_10y['China_10Y'] = pd.to_numeric(china_10y['China_10Y'], errors='coerce')
china_10y.head()
china_2y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\China 2-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
china_2y = china_2y.set_index('Date').sort_index()
china_2y.columns = ['China_2Y']
china_2y['China_2Y'] = pd.to_numeric(china_2y['China_2Y'], errors='coerce')
china_2y.head()

            China_2Y
Date
2016-01-01     2.584
2016-02-01     2.498
2016-03-01     2.357
2016-04-01     2.591
2016-05-01     2.585

In [8]:
#India
India = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\processed\master_panel.csv',parse_dates=['date'], index_col='date')[['yield_10y', 'yield_2y']].copy()
India.columns = ['India_10Y', 'India_2Y']
India.head()

            India_10Y  India_2Y
date
2021-04-30    6.35670   4.25790
2021-05-31    6.25843   4.36907
2021-06-30    6.39280   4.57015
2021-07-31    6.22949   4.34746
2021-08-31    6.37140   4.22070

In [14]:
#Indonesia
indo_10y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Indonesia 10-Year Bond Yield Historical Data monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
indo_10y = indo_10y.set_index('Date').sort_index()
indo_10y.columns = ['indo_10Y']
indo_10y['indo_10Y'] = pd.to_numeric(indo_10y['indo_10Y'], errors='coerce')
indo_3y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Indonesia 3-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
indo_3y = indo_3y.set_index('Date').sort_index()
indo_3y.columns = ['indo_3Y']
indo_3y['indo_3Y'] = pd.to_numeric(indo_3y['indo_3Y'], errors='coerce')
indo_3y.head()

            indo_3Y
Date
2016-01-01    8.165
2016-02-01    7.951
2016-03-01    7.536
2016-04-01    7.368
2016-05-01    7.397

In [ ]:
#Brazil 
brazil_10y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Brazil 10-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
brazil_10y = brazil_10y.set_index('Date').sort_index()
brazil_10y.columns = ['brazil_10Y']
brazil_10y['brazil_10Y'] = pd.to_numeric(brazil_10y['brazil_10Y'], errors='coerce')
brazil_2y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Brazil 2-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
brazil_2y = brazil_2y.set_index('Date').sort_index()
brazil_2y.columns = ['brazil_2y']
brazil_2y['brazil_2y'] = pd.to_numeric(brazil_2y['brazil_2y'], errors='coerce')
brazil_2y.head()

            brazil_2y
Date
2016-01-01      14.99
2016-02-01      14.60
2016-03-01      13.67
2016-04-01      12.74
2016-05-01      12.88

In [17]:
#Malaysia
malay_10y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Malaysia 10-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
malay_10y = malay_10y.set_index('Date').sort_index()
malay_10y.columns = ['malay_10Y']
malay_10y['malay_10Y'] = pd.to_numeric(malay_10y['malay_10Y'], errors='coerce')
malay_3y = pd.read_csv(r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international\Malaysia 3-Year Bond Yield Historical Data_monthly.csv',usecols=['Date', 'Price'],parse_dates=['Date'],dayfirst=False)
malay_3y = malay_3y.set_index('Date').sort_index()
malay_3y.columns = ['malay_3y']
malay_3y['malay_3y'] = pd.to_numeric(malay_3y['malay_3y'], errors='coerce')
malay_3y.head()

            malay_3y
Date
2016-01-01     3.219
2016-02-01     3.321
2016-03-01     3.235
2016-04-01     3.290
2016-05-01     3.270

In [ ]:
import os
path = r'C:\Users\Spandan Dutta\econometrics_project\data\raw\international'
files = os.listdir(path)
for f in files:
    print(f)

Brazil 10-Year Bond Yield Historical Data_monthly.csv
Brazil 2-Year Bond Yield Historical Data_monthly.csv
China 10-Year Bond Yield Historical Data_monthly.csv
China 2-Year Bond Yield Historical Data_monthly.csv
Indonesia 10-Year Bond Yield Historical Data monthly.csv
Indonesia 3-Year Bond Yield Historical Data_monthly.csv
Malaysia 10-Year Bond Yield Historical Data_monthly.csv
Malaysia 3-Year Bond Yield Historical Data_monthly.csv